module.exports.config = {
  name: "meme",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Tuấn",
  description: "Random ảnh memevn",
  commandCategory: "Ảnh",
  usages: "memevn",
  cooldowns: 2,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
    
};

module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
    var link = [
"https://i.imgur.com/Jy5bCx2.jpg",
"https://i.imgur.com/yAtQUQu.jpg",
"https://i.imgur.com/MdhUHdV.jpg",
"https://i.imgur.com/KKmkIop.jpg",
"https://i.imgur.com/Adr4be1.jpg",
"https://i.imgur.com/s2giVqG.jpg",
"https://i.imgur.com/OLp3vhz.png",
"https://i.imgur.com/W2VGWqb.jpg",
"https://i.imgur.com/EBJcGFf.jpg",
"https://i.imgur.com/WYchdJG.jpg",
"https://i.imgur.com/dwVGQD6.jpg",
"https://i.imgur.com/3MbRb7U.jpg",
"https://i.imgur.com/cpzJeWp.jpg",
"https://i.imgur.com/D281oqO.jpg",
"https://i.imgur.com/JNKZA8P.jpg",
"https://i.imgur.com/5Nl04oP.jpg",
"https://i.imgur.com/wMxv9qa.jpg",
"https://i.imgur.com/UmfVLiD.jpg",
"https://i.imgur.com/fIpWNOy.jpg",
"https://i.imgur.com/GtcFh2Y.jpg",
"https://i.imgur.com/1HFEzu0.jpg",
"https://i.imgur.com/qSuCJzj.jpg",
"https://i.imgur.com/AZpbUsz.png",
"https://i.imgur.com/JtGE76p.jpg",
"https://i.imgur.com/ZJYI9pQ.jpg",
"https://i.imgur.com/nC9aCJZ.jpg",
"https://i.imgur.com/BI9eFuS.jpg",
"https://i.imgur.com/ZPUguG2.jpg",
"https://i.imgur.com/IA8Dl6W.jpg",
"https://i.imgur.com/xYvvgIS.jpg",
"https://i.imgur.com/P8Cuobo.jpg",
"https://i.imgur.com/ZB3G2XY.jpg",
"https://i.imgur.com/X8dyJFy.jpg",
"https://i.imgur.com/DXbEYs5.jpg",
"https://i.imgur.com/Kp4oBzH.jpg",
"https://i.imgur.com/JJ8JcG9.jpg",
"https://i.imgur.com/pcqGJOv.jpg",
"https://i.imgur.com/2IYFkGg.jpg",
"https://i.imgur.com/YeCs17L.jpg",
"https://i.imgur.com/mnhqSFj.jpg",
"https://i.imgur.com/LvstoaU.jpg",
"https://i.imgur.com/b5NnMbM.jpg",
"https://i.imgur.com/ULLpJma.jpg",
"https://i.imgur.com/NCzHoTX.jpg",
"https://i.imgur.com/aaQWZ8N.jpg",
"https://i.imgur.com/uwOv32N.jpg",
"https://i.imgur.com/t7H72wa.jpg",
"https://i.imgur.com/pPkUzJM.jpg",
"https://i.imgur.com/CEMGJ9W.jpg",
"https://i.imgur.com/69MsxdV.jpg",
"https://i.imgur.com/CoRAATY.jpg",
"https://i.imgur.com/iKiTo19.jpg",
"https://i.imgur.com/QoADPi6.jpg",
"https://i.imgur.com/NE6pYOD.jpg",
"https://i.imgur.com/Sbdp9Q5.jpg",
"https://i.imgur.com/iyhrTIB.jpg",
"https://i.imgur.com/BhVuozj.jpg",
"https://i.imgur.com/AWwaVk5.jpg",
"https://i.imgur.com/N3cXnyz.jpg",
"https://i.imgur.com/ainmNyF.jpg",
"https://i.imgur.com/6lBaro7.jpg",
"https://i.imgur.com/NKHnOtG.jpg",
"https://i.imgur.com/lFgCxIp.jpg",
"https://i.imgur.com/deMh8rW.jpg",
"https://i.imgur.com/zrt9feD.jpg",
"https://i.imgur.com/BYweLzF.jpg",
"https://i.imgur.com/iTfOrVo.jpg",
"https://i.imgur.com/RqtXFd9.jpg",
"https://i.imgur.com/zg8CtDt.jpg",
"https://i.imgur.com/9JlxPbT.jpg",
"https://i.imgur.com/54y9zXR.jpg",
"https://i.imgur.com/sngHX7c.jpg",
"https://i.imgur.com/NcV9XUO.jpg",
"https://i.imgur.com/HD4ycMD.jpg",
"https://i.imgur.com/x7dMikz.jpg",
"https://i.imgur.com/n5Q11Sk.jpg",
"https://i.imgur.com/pda9nUS.jpg",
"https://i.imgur.com/LDVmIci.jpg",
"https://i.imgur.com/iU5AP0e.jpg",
"https://i.imgur.com/TH8lnWp.jpg",
"https://i.imgur.com/qBDUzw5.jpg",
"https://i.imgur.com/8TQsRNy.jpg",
"https://i.imgur.com/bqIPacl.png",
"https://i.imgur.com/WOZK81t.jpg",
"https://i.imgur.com/XmuQRTe.jpg",
     ];
     var callback = () => api.sendMessage({body:`𝐌𝐞𝐦𝐞 𝐜𝐮̛̣𝐜 𝐡𝐚̀𝐢 🤣`,attachment: fs.createReadStream(__dirname + "/cache/1.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/1.jpg"));  
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/1.jpg")).on("close",() => callback());
   };